import { Product } from "./types"

export const products: Product[] = [
  {
    id: "prod_001",
    title: "iPhone 15 Pro Max",
    handle: "iphone-15-pro-max",
    subtitle: "Smartphone flagship dengan chip A17 Pro",
    description: "iPhone 15 Pro Max menghadirkan desain titanium yang kuat dan ringan, chip A17 Pro untuk performa gaming luar biasa, dan sistem kamera revolusioner dengan lensa telephoto 5x.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Iphone_2_qveblq.webp",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Iphone_1_nqz3cc.webp",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Iphone_3_f1gunn.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Iphone_3_f1gunn.jpg",
    ],
    category_id: "pcat_hp",
    collection_ids: ["col_new", "col_tech"],
    tags: ["apple", "smartphone", "5g", " flagship"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Natural Titanium", "Blue Titanium", "White Titanium"] },
      { id: "opt_storage", title: "Storage", values: ["256GB", "512GB", "1TB"] },
    ],
    variants: [
      { id: "var_001_nat_256", title: "Natural Titanium / 256GB", sku: "IP15PM-NT-256", price: 19999000, inventory_quantity: 45, options: { Warna: "Natural Titanium", Storage: "256GB" } },
      { id: "var_001_nat_512", title: "Natural Titanium / 512GB", sku: "IP15PM-NT-512", price: 22999000, inventory_quantity: 32, options: { Warna: "Natural Titanium", Storage: "512GB" } },
      { id: "var_001_blu_256", title: "Blue Titanium / 256GB", sku: "IP15PM-BT-256", price: 19999000, original_price: 20999000, inventory_quantity: 28, options: { Warna: "Blue Titanium", Storage: "256GB" } },
      { id: "var_001_wht_512", title: "White Titanium / 512GB", sku: "IP15PM-WT-512", price: 22999000, inventory_quantity: 15, options: { Warna: "White Titanium", Storage: "512GB" } },
    ],
    created_at: "2024-09-15T08:00:00Z",
    updated_at: "2025-03-20T10:30:00Z",
  },
  {
    id: "prod_002",
    title: "MacBook Air M3",
    handle: "macbook-air-m3",
    subtitle: "Laptop tipis dan ringan dengan chip M3",
    description: "MacBook Air dengan chip M3 menghadirkan performa luar biasa dalam desain yang sangat tipis dan ringan. Layar Liquid Retina 13.6 inci dengan dukungan untuk 1 miliar warna.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Macbook_1_yrmyfo.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264714/Macbook_2_bjn9zt.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264713/Macbook_3_ts5qb4.jpg",
    ],
    category_id: "pcat_laptop",
    collection_ids: ["col_new", "col_tech"],
    tags: ["apple", "laptop", "m3", "productivity"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Midnight", "Starlight", "Space Grey"] },
      { id: "opt_ram", title: "RAM", values: ["8GB", "16GB"] },
    ],
    variants: [
      { id: "var_002_mid_8", title: "Midnight / 8GB", sku: "MBA-M3-M-8", price: 17999000, inventory_quantity: 20, options: { Warna: "Midnight", RAM: "8GB" } },
      { id: "var_002_mid_16", title: "Midnight / 16GB", sku: "MBA-M3-M-16", price: 21999000, inventory_quantity: 12, options: { Warna: "Midnight", RAM: "16GB" } },
      { id: "var_002_str_8", title: "Starlight / 8GB", sku: "MBA-M3-S-8", price: 17999000, original_price: 18999000, inventory_quantity: 18, options: { Warna: "Starlight", RAM: "8GB" } },
    ],
    created_at: "2024-03-01T08:00:00Z",
    updated_at: "2025-02-15T14:00:00Z",
  },
  {
    id: "prod_003",
    title: "Sony WH-1000XM5",
    handle: "sony-wh1000xm5",
    subtitle: "Noise cancelling headphones premium",
    description: "WH-1000XM5 dengan 8 microphone untuk noise cancelling yang tak tertandingi. Driver baru 30mm menghadirkan suara yang jernih dan natural dengan bass dalam.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264713/Sony_WH_1_yzifmq.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264713/Sony_WH_2_qzurdi.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264648/Sony_WH_3_dkhxmk.jpg",
    ],
    category_id: "pcat_audio",
    collection_ids: ["col_new", "col_sale"],
    tags: ["sony", "headphone", "noise-cancelling", "audio"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Black", "Silver"] },
    ],
    variants: [
      { id: "var_003_blk", title: "Black", sku: "SONY-XM5-BLK", price: 4299000, original_price: 5499000, inventory_quantity: 55, options: { Warna: "Black" } },
      { id: "var_003_slv", title: "Silver", sku: "SONY-XM5-SLV", price: 4299000, original_price: 5499000, inventory_quantity: 30, options: { Warna: "Silver" } },
    ],
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2025-04-01T09:00:00Z",
  },
  {
    id: "prod_004",
    title: "Nike Air Force 1 '07",
    handle: "nike-air-force-1-07",
    subtitle: "Sneaker klasik yang timeless",
    description: "Nike Air Force 1 '07 adalah sneaker ikonik yang menghadirkan gaya klasik dengan kenyamanan modern. Upper kulit premium dengan sol Air-Sole untuk cushioning sepanjang hari.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264598/Nike_3_xtqnip.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264619/Nike_1_yxyagj.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264598/Nike_2_bnrm8y.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264598/Nike_3_xtqnip.jpg",
    ],
    category_id: "pcat_pria",
    collection_ids: ["col_new", "col_lifestyle"],
    tags: ["nike", "sneakers", "shoes", "fashion"],
    options: [
      { id: "opt_size", title: "Ukuran", values: ["40", "41", "42", "43", "44"] },
    ],
    variants: [
      { id: "var_004_40", title: "40", sku: "NIKE-AF1-40", price: 1549000, inventory_quantity: 8, options: { Ukuran: "40" } },
      { id: "var_004_41", title: "41", sku: "NIKE-AF1-41", price: 1549000, inventory_quantity: 15, options: { Ukuran: "41" } },
      { id: "var_004_42", title: "42", sku: "NIKE-AF1-42", price: 1549000, inventory_quantity: 22, options: { Ukuran: "42" } },
      { id: "var_004_43", title: "43", sku: "NIKE-AF1-43", price: 1549000, inventory_quantity: 18, options: { Ukuran: "43" } },
      { id: "var_004_44", title: "44", sku: "NIKE-AF1-44", price: 1549000, original_price: 1699000, inventory_quantity: 5, options: { Ukuran: "44" } },
    ],
    created_at: "2023-08-20T08:00:00Z",
    updated_at: "2025-03-10T11:00:00Z",
  },
  {
    id: "prod_005",
    title: "Samsung Galaxy S24 Ultra",
    handle: "samsung-galaxy-s24-ultra",
    subtitle: "Smartphone AI dengan S Pen",
    description: "Galaxy S24 Ultra dengan Galaxy AI, S Pen built-in, dan kamera 200MP. Layar QHD+ 6.8 inci dengan adaptive refresh rate 1-120Hz.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Samsung_3_hvzjt0.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Samsung_1_bynelo.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264598/Samsung_2_oj67qz.jpg",
    ],
    category_id: "pcat_hp",
    collection_ids: ["col_new"],
    tags: ["samsung", "smartphone", "android", "s-pen"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Titanium Grey", "Titanium Black", "Titanium Violet"] },
      { id: "opt_storage", title: "Storage", values: ["256GB", "512GB", "1TB"] },
    ],
    variants: [
      { id: "var_005_gry_256", title: "Titanium Grey / 256GB", sku: "S24U-GY-256", price: 18999000, inventory_quantity: 35, options: { Warna: "Titanium Grey", Storage: "256GB" } },
      { id: "var_005_blk_512", title: "Titanium Black / 512GB", sku: "S24U-BK-512", price: 21499000, inventory_quantity: 20, options: { Warna: "Titanium Black", Storage: "512GB" } },
    ],
    created_at: "2024-01-25T08:00:00Z",
    updated_at: "2025-04-05T10:00:00Z",
  },
  {
    id: "prod_006",
    title: "AirPods Pro 2",
    handle: "airpods-pro-2",
    subtitle: "Earbuds dengan noise cancelling aktif",
    description: "AirPods Pro 2 dengan chip H2, noise cancelling 2x lebih baik, dan Adaptive Transparency. Case MagSafe dengan speaker built-in dan Precision Finding.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Airpods_1_urd0mt.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Airpods_2_syjgjw.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Airpods_3_li1jni.jpg",
    ],
    category_id: "pcat_audio",
    collection_ids: ["col_sale", "col_tech"],
    tags: ["apple", "earbuds", "wireless", "audio"],
    options: [],
    variants: [
      { id: "var_006", title: "Default", sku: "APP-PRO2", price: 3299000, original_price: 3999000, inventory_quantity: 80, options: {} },
    ],
    created_at: "2023-09-10T08:00:00Z",
    updated_at: "2025-04-10T09:00:00Z",
  },
  {
    id: "prod_007",
    title: "Logitech MX Master 3S",
    handle: "logitech-mx-master-3s",
    subtitle: "Mouse wireless untuk produktivitas",
    description: "MX Master 3S dengan sensor 8000 DPI, scroll MagSpeed elektromagnetik, dan click senyap. Ergonomis untuk penggunaan seharian.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Logitech_1_pxk79z.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Logitech_2_klxvqm.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264596/Logitech_3_ohjvyp.jpg",
    ],
    category_id: "pcat_elektronik",
    collection_ids: ["col_tech"],
    tags: ["logitech", "mouse", "wireless", "productivity"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Graphite", "Pale Grey"] },
    ],
    variants: [
      { id: "var_007_gph", title: "Graphite", sku: "LOG-MX3S-GRP", price: 1199000, inventory_quantity: 40, options: { Warna: "Graphite" } },
      { id: "var_007_pgy", title: "Pale Grey", sku: "LOG-MX3S-PGY", price: 1199000, inventory_quantity: 25, options: { Warna: "Pale Grey" } },
    ],
    created_at: "2023-06-15T08:00:00Z",
    updated_at: "2025-02-28T10:00:00Z",
  },
  {
    id: "prod_008",
    title: "Anker 737 Power Bank 24000mAh",
    handle: "anker-737-power-bank",
    subtitle: "Power bank dengan layar digital",
    description: "Power Bank 737 dengan kapasitas 24000mAh, output 140W, dan layar TFT digital yang menampilkan informasi charging real-time.",
    status: "published",
    thumbnail: "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Anker_1_s1io16.jpg",
    images: [
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264597/Anker_2_fmfa9c.jpg",
      "https://res.cloudinary.com/dicwfbdgz/image/upload/v1777264596/Anker_3_xg1ssh.jpg",
    ],
    category_id: "pcat_elektronik",
    collection_ids: ["col_tech"],
    tags: ["anker", "power-bank", "charging", "accessories"],
    options: [],
    variants: [
      { id: "var_008", title: "Default", sku: "ANK-737-24K", price: 1299000, inventory_quantity: 60, options: {} },
    ],
    created_at: "2023-11-05T08:00:00Z",
    updated_at: "2025-03-15T09:00:00Z",
  },
  {
    id: "prod_009",
    title: "Herschel Classic Backpack",
    handle: "herschel-classic-backpack",
    subtitle: "Tas ransel klasik untuk sehari-hari",
    description: "Herschel Classic Backpack XL dengan kompartmen laptop 15 inci, saku depan dengan organizer, dan strap bahu yang nyaman.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-herschel-classic-backpack/600/600",
    images: ["https://picsum.photos/seed/shopedia-herschel-classic-backpack-1/800/800"],
    category_id: "pcat_pria",
    collection_ids: ["col_sale", "col_lifestyle"],
    tags: ["herschel", "backpack", "bag", "fashion"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Black", "Navy", "Olive"] },
    ],
    variants: [
      { id: "var_009_blk", title: "Black", sku: "HSC-CLSC-BLK", price: 899000, original_price: 1199000, inventory_quantity: 25, options: { Warna: "Black" } },
      { id: "var_009_nvy", title: "Navy", sku: "HSC-CLSC-NVY", price: 899000, original_price: 1199000, inventory_quantity: 18, options: { Warna: "Navy" } },
    ],
    created_at: "2023-07-20T08:00:00Z",
    updated_at: "2025-04-08T10:00:00Z",
  },
  {
    id: "prod_010",
    title: "Keychron K2 Pro",
    handle: "keychron-k2-pro",
    subtitle: "Mechanical keyboard wireless 75%",
    description: "Keychron K2 Pro dengan layout 75%, hot-swappable switches, QMK/VIA support, dan koneksi Bluetooth 5.1 + wired. Perfect untuk produktivitas dan gaming.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-keychron-k2-pro/600/600",
    images: ["https://picsum.photos/seed/shopedia-keychron-k2-pro-1/800/800"],
    category_id: "pcat_elektronik",
    collection_ids: ["col_tech"],
    tags: ["keychron", "keyboard", "mechanical", "wireless"],
    options: [
      { id: "opt_switch", title: "Switch", values: ["Gateron Red", "Gateron Brown", "Gateron Blue"] },
    ],
    variants: [
      { id: "var_010_red", title: "Gateron Red", sku: "KCK2P-RED", price: 1499000, inventory_quantity: 15, options: { Switch: "Gateron Red" } },
      { id: "var_010_brn", title: "Gateron Brown", sku: "KCK2P-BRN", price: 1499000, inventory_quantity: 20, options: { Switch: "Gateron Brown" } },
    ],
    created_at: "2023-10-10T08:00:00Z",
    updated_at: "2025-03-25T09:00:00Z",
  },
  {
    id: "prod_011",
    title: "Yoga Mat Premium 6mm",
    handle: "yoga-mat-premium-6mm",
    subtitle: "Matras yoga anti-slip dengan garis alignment",
    description: "Yoga mat TPE eco-friendly 6mm dengan tekstur anti-slip dua sisi dan garis alignment laser untuk postur yang sempurna.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-yoga-mat-premium-6mm/600/600",
    images: ["https://picsum.photos/seed/shopedia-yoga-mat-premium-6mm-1/800/800"],
    category_id: "pcat_olahraga",
    collection_ids: ["col_lifestyle"],
    tags: ["yoga", "fitness", "mat", "exercise"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Purple", "Teal", "Rose"] },
    ],
    variants: [
      { id: "var_011_pur", title: "Purple", sku: "YOGA-6MM-PUR", price: 349000, inventory_quantity: 50, options: { Warna: "Purple" } },
      { id: "var_011_tea", title: "Teal", sku: "YOGA-6MM-TEA", price: 349000, inventory_quantity: 45, options: { Warna: "Teal" } },
    ],
    created_at: "2023-05-15T08:00:00Z",
    updated_at: "2025-02-20T09:00:00Z",
  },
  {
    id: "prod_012",
    title: "Tefal Express Steam Iron",
    handle: "tefal-express-steam-iron",
    subtitle: "Setrika uap 2600W dengan Durilium AirGlide",
    description: "Setrika uap Tefal Express dengan daya 2600W, semburan uap 220g/menit, dan alas Durilium AirGlide untuk gesekan minimal.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-tefal-express-steam-iron/600/600",
    images: ["https://picsum.photos/seed/shopedia-tefal-express-steam-iron-1/800/800"],
    category_id: "pcat_rumah",
    collection_ids: ["col_sale"],
    tags: ["tefal", "iron", "home", "appliance"],
    options: [],
    variants: [
      { id: "var_012", title: "Default", sku: "TEF-EXP-2600", price: 699000, original_price: 899000, inventory_quantity: 35, options: {} },
    ],
    created_at: "2023-09-01T08:00:00Z",
    updated_at: "2025-04-12T09:00:00Z",
  },
  {
    id: "prod_013",
    title: "Moleskine Classic Notebook",
    handle: "moleskine-classic-notebook",
    subtitle: "Notebook ikonik dengan kertas premium",
    description: "Moleskine Classic Hard Cover notebook dengan kertas FSC-certified 70 gsm, pena loop, dan elastic closure. Ukuran Large (13x21cm).",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-moleskine-classic-notebook/600/600",
    images: ["https://picsum.photos/seed/shopedia-moleskine-classic-notebook-1/800/800"],
    category_id: "pcat_buku",
    collection_ids: ["col_lifestyle"],
    tags: ["moleskine", "notebook", "stationery", "writing"],
    options: [
      { id: "opt_color", title: "Warna", values: ["Black", "Red", "Blue"] },
    ],
    variants: [
      { id: "var_013_blk", title: "Black", sku: "MSK-CLS-BLK", price: 289000, inventory_quantity: 70, options: { Warna: "Black" } },
      { id: "var_013_red", title: "Red", sku: "MSK-CLS-RED", price: 289000, inventory_quantity: 40, options: { Warna: "Red" } },
    ],
    created_at: "2023-04-10T08:00:00Z",
    updated_at: "2025-03-05T09:00:00Z",
  },
  {
    id: "prod_014",
    title: "Uniqlo Airism T-Shirt",
    handle: "uniqlo-airism-tshirt",
    subtitle: "Kaos breathable dengan teknologi AIRism",
    description: "Kaos Uniqlo AIRism dengan teknologi penyerap kelembaban, cepat kering, dan anti-bau. Cocok untuk aktivitas sehari-hari maupun olahraga.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-uniqlo-airism-tshirt/600/600",
    images: ["https://picsum.photos/seed/shopedia-uniqlo-airism-tshirt-1/800/800"],
    category_id: "pcat_pria",
    collection_ids: ["col_lifestyle"],
    tags: ["uniqlo", "tshirt", "fashion", "casual"],
    options: [
      { id: "opt_size", title: "Ukuran", values: ["S", "M", "L", "XL"] },
      { id: "opt_color", title: "Warna", values: ["White", "Black", "Navy", "Grey"] },
    ],
    variants: [
      { id: "var_014_s_wht", title: "S / White", sku: "UNQ-AIR-S-WHT", price: 149000, inventory_quantity: 30, options: { Ukuran: "S", Warna: "White" } },
      { id: "var_014_m_blk", title: "M / Black", sku: "UNQ-AIR-M-BLK", price: 149000, inventory_quantity: 45, options: { Ukuran: "M", Warna: "Black" } },
      { id: "var_014_l_nvy", title: "L / Navy", sku: "UNQ-AIR-L-NVY", price: 149000, inventory_quantity: 35, options: { Ukuran: "L", Warna: "Navy" } },
      { id: "var_014_xl_gry", title: "XL / Grey", sku: "UNQ-AIR-XL-GRY", price: 149000, inventory_quantity: 20, options: { Ukuran: "XL", Warna: "Grey" } },
    ],
    created_at: "2023-06-01T08:00:00Z",
    updated_at: "2025-04-01T09:00:00Z",
  },
  {
    id: "prod_015",
    title: "Philips Air Fryer HD9252",
    handle: "philips-air-fryer-hd9252",
    subtitle: "Air fryer dengan Rapid Air Technology",
    description: "Philips Air Fryer HD9252 dengan Rapid Air Technology, kapasitas 0.8kg, dan touch screen digital. Masak dengan 90% lebih sedikit lemak.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-philips-air-fryer-hd9252/600/600",
    images: ["https://picsum.photos/seed/shopedia-philips-air-fryer-hd9252-1/800/800"],
    category_id: "pcat_rumah",
    collection_ids: ["col_sale"],
    tags: ["philips", "air-fryer", "kitchen", "cooking"],
    options: [],
    variants: [
      { id: "var_015", title: "Default", sku: "PHI-AF-HD9252", price: 1799000, original_price: 2499000, inventory_quantity: 22, options: {} },
    ],
    created_at: "2023-08-01T08:00:00Z",
    updated_at: "2025-04-15T09:00:00Z",
  },
  {
    id: "prod_016",
    title: "Dumbbell Set Adjustable 20kg",
    handle: "dumbbell-set-adjustable-20kg",
    subtitle: "Set dumbbell adjustable 2-20kg",
    description: "Set dumbbell adjustable dengan berat 2-20kg per tangan. Plate besi berlapis karet, handle ergonomis dengan grip anti-slip.",
    status: "published",
    thumbnail: "https://picsum.photos/seed/shopedia-dumbbell-set-adjustable-20kg/600/600",
    images: ["https://picsum.photos/seed/shopedia-dumbbell-set-adjustable-20kg-1/800/800"],
    category_id: "pcat_olahraga",
    collection_ids: ["col_lifestyle"],
    tags: ["dumbbell", "fitness", "gym", "home-workout"],
    options: [],
    variants: [
      { id: "var_016", title: "Default", sku: "DB-ADJ-20KG", price: 599000, inventory_quantity: 28, options: {} },
    ],
    created_at: "2023-07-01T08:00:00Z",
    updated_at: "2025-03-20T09:00:00Z",
  },
]
